SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycGx3Y2hhbWd6am1qbW1rcG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDE4MzksImV4cCI6MjA2NjE3NzgzOX0.2cDqlLvZmcCNsd4-o01fXQd3f5wNZWy6lhDKLx82mtg"

AUTH_PASSWORD = "Foster31!!"
AUTH_PASSWORD_TEAM = "johnny99"
